---
before_install: 
- pip install Pillow pycrypto
- pip install -U setuptools
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
python: "2.7"
script: 
- make test
install: 
- python bootstrap.py
- bin/buildout -Nq
after_script: 
- cat app.log
language: python
